### ISSUE TITLE
(How) Does this work?

### ISSUE THREAD

**Issue by VusyBery** [J-Vernay/jvpatcher-great-ace-attorney#1]
Sorry, I know this isn't really an issue and this might be inappropriate to put here, sorry in advance, but this is the closest to a comment section for me to ask questions.

Is this project currently working and if so, could you explain step-by-step how to use it? I'm not very knowledgeable about this sort of thing, so sorry again.

**Comment by J-Vernay** [comment]
Hi! I stopped working on it for a long time.

The minimal viable code is working (eg. extracting the game files in a somewhat readable format, and compressing them back). So it can be used as learning material if you want to do your own code.

I have plan to come back to it some time... but now that I am full time employee, I have less time to dedicate to it, ^^'
